/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import api.utils.EnvUtil;
import io.vertx.core.http.HttpServerOptions;
import io.vertx.reactivex.core.Vertx;
import io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory;

public class Main {


    public static void main(String[] args) {
        var vertx = Vertx.vertx();

        OpenAPI3RouterFactory.rxCreate(vertx, "api.yml")
                .flatMap(factory -> {
                    var router = factory.getRouter();
                    var server = vertx.createHttpServer(
                            new HttpServerOptions()
                                    .setPort(
                                            Integer.valueOf(EnvUtil.getEnv("PORT","8080"))
                                    ));

                    return server.requestHandler(router).rxListen();
                }).subscribe(server -> System.out.println("up and running"), Throwable::printStackTrace);
    }
}
