/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import api.modules.HttpHandlersModule;
import api.modules.PersistenceModule;
import api.utils.EnvUtil;
import io.vertx.core.http.HttpServerOptions;
import io.vertx.reactivex.core.Vertx;
import io.vertx.reactivex.ext.web.Router;
import io.vertx.reactivex.ext.web.api.contract.openapi3.OpenAPI3RouterFactory;
import io.vertx.reactivex.ext.web.handler.BodyHandler;
import io.vertx.reactivex.ext.web.handler.StaticHandler;

public class Main {


    public static void main(String[] args) {
        var vertx = Vertx.vertx();

        var persistence = PersistenceModule.create(vertx,
                new PersistenceModule.PersistenceConfig(
                        "localhost",
                        27017,
                        "form3"
                ));

        var httpHandlers = HttpHandlersModule.create(persistence);

        OpenAPI3RouterFactory.rxCreate(vertx, "webroot/api.yml")
                .flatMap(factory -> {
                    var router = factory.getRouter();
                    router.route("/*").handler(StaticHandler.create());
                    var paymentSubRouter = Router.router(vertx);
                    paymentSubRouter.route().handler(BodyHandler.create());
                    httpHandlers.forEach(h -> paymentSubRouter.route(h.getLeft(), h.getMiddle()).handler(h.getRight()));
                    router.mountSubRouter("/api/v1",paymentSubRouter);
                    var server = vertx.createHttpServer(
                            new HttpServerOptions()
                                    .setPort(
                                            Integer.valueOf(EnvUtil.getEnv("PORT", "8080"))
                                    ));

                    return server.requestHandler(router).rxListen();
                }).subscribe(server -> System.out.println("up and running"), Throwable::printStackTrace);
    }
}
