/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api;

import api.modules.ApplicationModule;
import api.modules.PersistenceModule;
import api.utils.EnvUtil;
import io.vertx.reactivex.core.Vertx;

public class Main {


    public static void main(String[] args) {
        var vertx = Vertx.vertx();
        var application = ApplicationModule.createApplication(vertx,
                new ApplicationModule.EnvironmentConfig(
                        new PersistenceModule.PersistenceConfig(
                                EnvUtil.getEnv("MONGO_HOST"),
                                Integer.valueOf(EnvUtil.getEnv("MONGO_PORT")),
                                EnvUtil.getEnv("MONGO_DB_NAME")
                        ),
                        Integer.valueOf(EnvUtil.getEnv("SERVER_PORT"))));

        application
                .subscribe(server -> System.out.println("up and running"), Throwable::printStackTrace);
    }
}
